package aethersetgen

var (
	timePeriods = []string{
		"Old Stone Age",
		"New Stone Age",
		"Bronze Age",
		"Iron Age",
		"Persian Empire",
		"Hellenism",
		"Roman Empire",
		"Byzantine Empire",
		"Dark Ages",
		"Medieval Ages",
		"Age of Exploration",
		"Rennaissance",
		"Colonialism",
		"Industrial Revolution",
		"Victorian Era",
		"Turn of the Century",
		"World War I",
		"Prohibition/Depression",
		"World War II",
		"Rock and Roll Era",
		"21st Century",
		"Post-Modern",
		"Near Future",
		"Future",
		"Distant Future",
	}

	technologies = []string{
		"Technology of the Time",
		"Advanced",
		"Weird",
		"Stone",
		"Bronze",
		"Iron",
		"Gear",
		"Gunpowder",
		"Rennaissance",
		"Steam",
		"Combustion",
		"Diesel",
		"Air",
		"Fission",
		"Fusion",
		"Space",
		"Cyber",
		"Genetic",
		"Gravity",
		"Dark Energy",
	}

	tones = []string{
		"Action",
		"Black",
		"Dark",
		"Dystopia",
		"Heroic",
		"Noir",
		"Romance",
		"Supernatural",
		"Tragedy",
		"Utopia",
		"Comedy",
	}

	genres = []string{
		"Alternate History",
		"Classic",
		"Comedy",
		"Epic",
		"Fantasy",
		"High Fantasy",
		"Low Fantasy",
		"Horror",
		"Mystery",
		"Opera",
		"Punk",
		"Romance",
		"Science Fiction",
	}
)
